PATH_TO_PRETRAINED_MODELS = "../FeatureExtraction/models/" #"../PretrainedModels/"
PATH_TO_SAVED_MODELS = "./ckpt/"
PATH_TO_PERFORMACE = "./PerformanceLog/"
PATH_TO_CKPT = "./ckpt/"
LLM = ["llama-2-7b","qwen2_5-7b"]
LM = ["roberta-large","roberta-base","t5-base"]
WHISPER = ['whisper-large-v3']
AM = ['wavlm-large','hubert-xlarge-ls960-ft','wav2vec2-large-960h','wav2vec2-large-960h-lv60-self']

[MSPPODCAST]
PATH_TO_LABEL='/datas/store163/othsueh/Emo_analyze/6emo/test/msp_podcast_6emo.csv'
PATH_TO_AUDIO='/datas/store162/othsueh/MSP-Podcast/Audios'
PATH_TO_TRANSCRIPT='/datas/store162/othsueh/MSP-Podcast/Transcripts'
PATH_TO_DATASET='/datas/store162/othsueh/wds_6_test/MSP-Podcast'

[IEMOCAP]
PATH_TO_LABEL='/datas/store163/othsueh/Emo_analyze/6emo/test/iemocap_6emo.csv'
PATH_TO_AUDIO='/datas/store162/othsueh/IEMOCAP/Audios'
PATH_TO_DATASET='/datas/store162/othsueh/wds_6_test/IEMOCAP'

[CREMAD]
PATH_TO_LABEL='/datas/store163/othsueh/Emo_analyze/6emo/test/crema_d_6emo.csv'
PATH_TO_AUDIO='/datas/store162/othsueh/CREMA-D/AudioWAV'
PATH_TO_DATASET='/datas/store162/othsueh/wds_6_test/CREMA-D'

[TOTAL]
# 6 emotions
# 10% Version
# PATH_TO_LABEL='/datas/store163/othsueh/Emo_analyze/newset/train&val_6emo_eps0.045_small.csv'
# PATH_TO_DATASET='/datas/store162/othsueh/wds_6_exp_small'
# EXP Version
PATH_TO_LABEL='/datas/store163/othsueh/Emo_analyze/6emo/train&val/train&val_6emo_eps0.045_min5.csv'
PATH_TO_DATASET='/datas/store162/othsueh/wds_6_exp'
# Full Version
# PATH_TO_LABEL='/datas/store163/othsueh/Emo_analyze/6emo/train&val/train&val_6emo_original.csv'
# PATH_TO_DATASET='/datas/store162/othsueh/wds_6_org'

# Full emotions
# 10% Version
# PATH_TO_LABEL='/datas/store163/othsueh/Emo_analyze/newset/train&val_eps0.045_small.csv'
# PATH_TO_DATASET='/datas/store162/othsueh/webdataset_total_small'
# Full Version
# PATH_TO_LABEL='/datas/store163/othsueh/Emo_analyze/newset/train&val_eps0.045.csv'
# PATH_TO_DATASET='/datas/store162/othsueh/webdataset_total'
