PATH_TO_PRETRAINED_MODELS = "../FeatureExtraction/models/"
PATH_TO_SAVED_MODELS = "./ckpt/"
PATH_TO_PERFORMACE = "./PerformanceLog/"
PATH_TO_CKPT = "./ckpt/"
LLM = ["llama-2-7b","qwen2_5-7b"]
LM = ["roberta-large","roberta-base","t5-base"]
WHISPER = ['whisper-large-v3']
AM = ['wavlm-large','hubert-xlarge-ls960-ft','wav2vec2-large-960h','wav2vec2-large-960h-lv60-self']

[MSPPODCAST]
PATH_TO_LABEL='/datas/store162/othsueh/MSP-Podcast/Labels/emosuperb_consensus.csv'
PATH_TO_AUDIO='/datas/store162/othsueh/MSP-Podcast/Audios'
PATH_TO_TRANSCRIPT='/datas/store162/othsueh/MSP-Podcast/Transcripts'
PATH_TO_DATASET='/datas/store162/othsueh/webdataset_msppodcast'
