[base_config]
project = "Test Performance"
corpus = "TOTAL"
origin_upstream_url = "facebook/wav2vec2-base"
upstream_model = "wav2vec2-base"
epoch = 35
batch_size = 16
learning_rate = 5e-5
dropout = 0.2
patience = 5
verbose = true
seed = 42
tags = ["Full set","Exp","Dual Head"]
hidden_dim = 64
finetune_layers = 3
classifier_output_dim = 6
num_layers = 3
use_feature = false
use_gender = false
ckpt_name = "None"

# Remote
[[experiments]]
name = "Experiment Set retesting"
model_type = "UpstreamFinetune"
config = "base_config"

# [[experiments]]
# name = "Experiment Set retesting with Gender"
# model_type = "UpstreamGender"
# config = "base_config"
# config_update = { use_gender=true, tags = ["Full set","Exp","Gender Head","Dual Head"]}

# Entry needed to modify for test: project, ckpt_name, tags, model_type, use_gender, corpus
# [[experiments]]
# name = "IEMOCAP with Gender"
# model_type = "UpstreamGender"
# config = "base_config"
# config_update = { corpus = "IEMOCAP", ckpt_name = "CombineCorpus_Gender", tags = ["Gender Tune"] }

# [[experiments]]
# name = "CREMAD with Gender"
# model_type = "UpstreamGender"
# config = "base_config"
# config_update = { corpus = "CREMAD",ckpt_name = "CombineCorpus_Gender"}

# [[experiments]]
# name = "MSPPODCAST with Gender"
# model_type = "UpstreamGender"
# config = "base_config"
# config_update = { corpus = "MSPPODCAST",ckpt_name = "CombineCorpus_Gender", tags = ["Gender Tune"]}

# [[experiments]]
# name = "IEMOCAP with Base"
# model_type = "UpstreamFinetune"
# config = "base_config"
# config_update = { use_gender = false, corpus = "IEMOCAP", ckpt_name = "CombineCorpus_ORG", tags = ["Normal"] }

# [[experiments]]
# name = "CREMAD with Base"
# model_type = "UpstreamFinetune"
# config = "base_config"
# config_update = { corpus = "CREMAD",ckpt_name = "CombineCorpus_ORG"}

# [[experiments]]
# name = "MSPPODCAST with Base"
# model_type = "UpstreamFinetune"
# config = "base_config"
# config_update = { corpus = "MSPPODCAST",ckpt_name = "CombineCorpus_ORG"}

